In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('customer_shopping_behavior.csv')

In [3]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   str
 3   Item Purchased          3900 non-null   str
 4   Category                3900 non-null   str
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   str
 7   Size                    3900 non-null   str
 8   Color                   3900 non-null   str
 9   Season                  3900 non-null   str
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   str
 12  Shipping Type           3900 non-null   str
 13  Discount Applied        3900 non-null   str
 14  Promo Code Used         3900 non-null   str
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   str
 17  Frequency of Purchases  3900 non-null   str
dtypes: float64(1), int64(4), str(13)
memory usage: 835.9 KB

In [5]:
df.describe(include = 'all')

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
count,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900,3863.000000,3900,3900,3900,3900,3900.000000,3900,3900
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,6,2,2,NaN,6,7
top,NaN,NaN,Male,Blouse,Clothing,NaN,Montana,M,Olive,Spring,NaN,No,Free Shipping,No,No,NaN,PayPal,Every 3 Months
freq,NaN,NaN,2652,171,1737,NaN,96,1755,177,999,NaN,2847,675,2223,2223,NaN,677,584
mean,1950.500000,44.068462,NaN,NaN,NaN,59.764359,NaN,NaN,NaN,NaN,3.750065,NaN,NaN,NaN,NaN,25.351538,NaN,NaN
std,1125.977353,15.207589,NaN,NaN,NaN,23.685392,NaN,NaN,NaN,NaN,0.716983,NaN,NaN,NaN,NaN,14.447125,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,975.750000,31.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
50%,1950.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.800000,NaN,NaN,NaN,NaN,25.000000,NaN,NaN
75%,2925.250000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,NaN,38.000000,NaN,NaN
max,3900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

### Data Cleaning & Preprocessing

In [7]:
# Missing Values
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

#### Replace the missing values by median. 
Replacing by 'Mean' is not a good option as mean can be affected my the outliers which may skew the distribution of the data. Median is a good choice over mean because it it robust to outliers. Medin withing the category not in general. Median for clothing item, should not consider the footware values.

#### Best practice
Consider the dataset:

10, 12, 13, 15, 100
- Mean = 30
- Median = 13
  
The outlier 100 pulls the mean upward, while the median remains representative of the typical observation.
Therefore, median imputation is often preferable for skewed numerical data or data containing outliers.
However, median imputation can reduce variability and distort relationships between variables, particularly when many values are missing.

#### Data type or situation	& Recommended approach
* Numerical data with outliers or skewness - Median
* Approximately normally distributed numerical data -	Mean, if appropriate
* Categorical data - Mode or an "Unknown" category
* Time-series data - Forward fill, interpolation, or domain-specific methods
* Large amounts of missing data - Investigate the cause; consider dropping or advanced imputation
* Missingness itself may be informative - Add a missing-value indicator

In [9]:
df['Review Rating'] = df.groupby('Category')['Review Rating'].transform(lambda x: x.fillna(x.median()))

In [10]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

#### Add underscores to the column names and make them all lower case. It helps a lot during writing the SQL and all the code.

In [12]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ','_')
df = df.rename(columns={'purchase_amount_(usd)':'purchase_amount'})

In [13]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='str')

### Feature Engineering

In [15]:
# Create a new column called 'age_group'
# qcut divides the data onto 4 equal sized groups
# Python knows how to sort the ages because pd.qcut() automatically uses the numerical values in your age column to determine the quantile boundaries. 
# You don't need to sort the DataFrame yourself.

labels = ['Young Adult', 'Adult', 'Middle-aged', 'Senior']
df['age_group'] = pd.qcut(df['age'], q=4, labels = labels)

In [16]:
df[['age', 'age_group']]

      age    age_group
0      55  Middle-aged
1      19  Young Adult
2      50  Middle-aged
3      21  Young Adult
4      45  Middle-aged
...   ...          ...
3895   40        Adult
3896   52  Middle-aged
3897   46  Middle-aged
3898   44        Adult
3899   52  Middle-aged

[3900 rows x 2 columns]

In [17]:
# Create a column purchase_frequency_days
# Map descriptive frequency data to frequency days.

frequency_mapping = {
    'Fortnightly': 14,
    'Weekly': 7,
    'Monthly': 30,
    'Quarterly': 90,
    'Bi-weekly': 14,
    'Annually': 365,
    'Every 3 Months': 90
}

df['purchase_frequency_days'] = df['frequency_of_purchases'].map(frequency_mapping)

In [18]:
df[['purchase_frequency_days', 'frequency_of_purchases']].head(10)

   purchase_frequency_days frequency_of_purchases
0                     14.0            Fortnightly
1                     14.0            Fortnightly
2                      7.0                 Weekly
3                      7.0                 Weekly
4                    365.0               Annually
5                      7.0                 Weekly
6                     90.0              Quarterly
7                      7.0                 Weekly
8                    365.0               Annually
9                     90.0              Quarterly

In [19]:
df[['discount_applied', 'promo_code_used']].head(10)

  discount_applied promo_code_used
0              Yes             Yes
1              Yes             Yes
2              Yes             Yes
3              Yes             Yes
4              Yes             Yes
5              Yes             Yes
6              Yes             Yes
7              Yes             Yes
8              Yes             Yes
9              Yes             Yes

In [20]:
# Do we actually need both these columns?
# Both of these columns look the same, let's check

(df['discount_applied'] == df['promo_code_used']).all()

True

In [21]:
# Both the columns have same data in them. Let's drop promo_code_used.

df = df.drop('promo_code_used', axis=1)

In [22]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purchase_frequency_days'],
      dtype='str')

## Connect to the Database

In [24]:
#pip install mysql-connector-python pandas sqlalchemy
!pip install pymysql sqlalchemy

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pymysql in C:\Users\anike\AppData\Roaming\Python\Python312\site-packages (1.2.3)
Requirement already satisfied: sqlalchemy in C:\Users\anike\AppData\Roaming\Python\Python312\site-packages (2.0.40)
Requirement already satisfied: greenlet>=1 in C:\Users\anike\AppData\Roaming\Python\Python312\site-packages (from sqlalchemy) (3.2.0)
Requirement already satisfied: typing-extensions>=4.6.0 in C:\Users\anike\AppData\Roaming\Python\Python312\site-packages (from sqlalchemy) (4.12.2)

WARNING: Ignoring invalid distribution ~ip (C:\Users\anike\AppData\Roaming\Python\Python312\site-packages)
WARNING: Ignoring invalid distribution ~orch (C:\Users\anike\AppData\Roaming\Python\Python312\site-packages)
WARNING: Ignoring invalid distribution ~ip (C:\Users\anike\AppData\Roaming\Python\Python312\site-packages)
WARNING: Ignoring invalid distribution ~orch (C:\Users\anike\AppData\Roaming\Python\Python312\site-packages)
WARNING: Ignoring invalid distribution ~ip (C:\Users\anike\AppData\Roaming\Python\Python312\site-packages)
WARNING: Ignoring invalid distribution ~orch (C:\Users\anike\AppData\Roaming\Python\Python312\site-packages)

In [25]:
#For MySQL

#pip install mysql-connector-python pandas sqlalchemy
# MySQL connection

import mysql.connector
from sqlalchemy import create_engine
from urllib.parse import quote_plus

username = "root"
password = quote_plus("#Chaitali@2402")
hostname = "localhost"
port = "3306"
database = "customer_shopping_behavior"

connection_str = (f"mysql+pymysql://{username}:{password}@{hostname}:{port}/{database}")
engine = create_engine(connection_str)

#engine = create_engine(f"mysql+pymysql://{username}:{password}@{hostname}:{port}/{database}")

# Write DataFrame to MySQL
table_name = "customer"   # choose any table name
df.to_sql(table_name, engine, if_exists="replace", index=False)

# Read back sample
pd.read_sql("SELECT * FROM customer LIMIT 5;", engine)

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,frequency_of_purchases,age_group,purchase_frequency_days
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,14,Venmo,Fortnightly,Middle-aged,14.0
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,2,Cash,Fortnightly,Young Adult,14.0
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,23,Credit Card,Weekly,Middle-aged,7.0
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,49,PayPal,Weekly,Young Adult,7.0
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,31,PayPal,Annually,Middle-aged,365.0

In [26]:
connection_str

'mysql+pymysql://root:%23Chaitali%402402@localhost:3306/customer_shopping_behavior'

In [27]:
#pip install pyodbc sqlalchemy

In [28]:
'''import pyodbc
import pandas as pd

# SQL Server connection details
server = 'SERVER01'  # e.g. localhost or SERVER01
database = 'Customer Shopping Behavior'
username = ''
password = ''

# Create connection
conn = pyodbc.connect(
    'DRIVER={ODBC Driver 18 for SQL Server};'
    f'SERVER={server};'
    f'DATABASE={database};'
    f'UID={username};'
    f'PWD={password};'
    'Encrypt=yes;'
    'TrustServerCertificate=yes;'
)

print("Connected to SQL Server successfully!")'''

'import pyodbc\nimport pandas as pd\n\n# SQL Server connection details\nserver = \'SERVER01\'  # e.g. localhost or SERVER01\ndatabase = \'Customer Shopping Behavior\'\nusername = \'\'\npassword = \'\'\n\n# Create connection\nconn = pyodbc.connect(\n    \'DRIVER={ODBC Driver 18 for SQL Server};\'\n    f\'SERVER={server};\'\n    f\'DATABASE={database};\'\n    f\'UID={username};\'\n    f\'PWD={password};\'\n    \'Encrypt=yes;\'\n    \'TrustServerCertificate=yes;\'\n)\n\nprint("Connected to SQL Server successfully!")'